env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  # project: ['./tsconfig.json', './tsconfig.node.json']
  # tsconfigRootDir: .
plugins:
  - '@typescript-eslint'
  - react
settings:
  react:
    version: 18.2.0
rules:
  'react/react-in-jsx-scope':
    - 0
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - sibling
        - parent
  no-unused-vars:
    - warn
  '@typescript-eslint/no-unused-vars':
    - warn
  no-undef:
    - warn
  react/prop-types:
    - warn
  import/no-unresolved:
    - error
    - ignore:
        - '\.svg'
